name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@master
        with:
          submodules: true

      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: main
          REPOSITORY: oliverdding/oliverdding.github.io
          BUILD_DIR: .
          GITHUB_TOKEN: ${{ secrets.ZOLA }}
